# List of commit statuses that must pass on the PR commit when it is r+-ed.
# (listed in same order as in the repo's branch protection settings)
pr_status = [
 "python-tests",
 "tools-build-success",
 "check-labels",
 "static-tests",
 "check-commits (commit-msg)",
 "check-commits (pr_check)",
 "Murdock",
 ]

# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
status = [
  "Murdock",
  "static-tests",
  "tools-build-success",
  ]

block_labels = [ "Process: missing approvals" ]

# Number of project members who must approve the PR (using GitHub Reviews)
# before it is pushed to master.
# This necessary even with the check-labels action (which checks for >1 ACKs),
# as that passes when there's no review or no special label set.
required_approvals = 1

# delete branch after successful merge
delete_merged_branches = true

# timeout for bors-initiated builds.
# unfortunately bors is not the only entity queuing builds, so this needs
# to take a full nightly build *plus* another full bors build *plus* some
# possible intermediate PR builds into accound.
# let's try ten hours (36000s)
timeout_sec = 36000

# "A marker in the PR description that indicates boilerplate that does not
# belong in the commit message."
#
# This basically cuts the whole description, which in our PR template starts
# with a comment:
cut_body_after = "<!--"
